### ISSUE TITLE
How to open ddp training

### ISSUE THREAD

**Issue by lsrrrrrrrrr** [NVlabs/catk#14]
Hi, thanks for your excellent work. How to start ddp training. 
I have tried to start - override /trainer: ddp in pre_bc.yaml. However, it does not work. Is there something I fail to adjust. Thanks for your time. 
```
defaults:
  **- override /trainer: ddp**
  - override /model: smart

model:
  model_config:
    lr: 5e-4
    lr_min_ratio: 1e-2
    token_processor:
      map_token_sampling: # open-loop
        num_k: 1 # for k nearest neighbors
        temp: 1.0 # uniform sampling
      agent_token_sampling: # closed-loop
        num_k: 1 # for
```
